#[http.routers]
#  [http.routers.redirecttohttps]
#    entryPoints = ["insecure"]
#    middlewares = ["httpsredirect"]
#    rule = "HostRegexp(`{host:.+}`)"
#    service = "noop"
#
#[http.services]
#  # noop service, the URL will be never called
#  [http.services.noop.loadBalancer]
#    [[http.services.noop.loadBalancer.servers]]
#      url = "http://192.168.0.1"
#
#[http.middlewares]
#  [http.middlewares.httpsredirect.redirectScheme]
#    scheme = "https"